### ISSUE TITLE
Using named arguments with RF 3.1.X and SikuliLibrary's keywords doesn't work

### ISSUE THREAD

**Issue by antonpaa** [rainmanwy/robotframework-SikuliLibrary#101]
Using RF 3.1.X (tested 3.1.0, 3.1.1, 3.1.2), which changed the dynamic API usage of RF, and a SikuliLibrary's keyword with named arguments, RF returns a failure:

> This library does not support keyword arguments.

And the debug log shows the following:

> java.lang.RuntimeException: This library does not support keyword arguments.
	at org.robotframework.remoteserver.library.DynamicApiRemoteLibrary.runKeyword(DynamicApiRemoteLibrary.java:56)
	at org.robotframework.remoteserver.servlet.ServerMethods.run_keyword(ServerMethods.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
	at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
	at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
	at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
	at org.apache.xmlrpc.webserver.XmlRpcServletServer.execute(XmlRpcServletServer.java:112)
	at org.apache.xmlrpc.webserver.XmlRpcServlet.doPost(XmlRpcServlet.java:196)
	at org.robotframework.remoteserver.servlet.RemoteServerServlet.doPost(RemoteServerServlet.java:122)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.robotframework.remoteserver.servlet.RemoteServerServlet.service(RemoteServerServlet.java:102)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:479)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:348)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:894)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:948)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:851)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
	at java.lang.Thread.run(Unknown Source)

When the same keyword is run using RF 3.0.4, it works as intended.
Screenshots of these cases added below.

RF 3.1.2:
![Using Click with RF 3.1.2](https://i.imgur.com/OhI11Ny.png)

RF 3.0.4:
![Using Click with RF 3.0.4](https://i.imgur.com/D8eAEuB.png)

I had a brief discussion with P. Klärck on RF's Slack:

> pekkaklarck   [19 minutes ago]
> https://github.com/robotframework/robotframework/issues/2930
> pekkaklarck   [17 minutes ago]
> The change wasn't done lightly but nobody objected it and there were no complaints during thr preview release cycle either. It won't be changed back anymore.
> pekkaklarck   [14 minutes ago]
> What needs to be changed is SikuliLibrary. Could you check does its issue tracker have an issue about it not being compatible with RF 3.1? If it doesn't, please submit one.

**Comment by rainmanwy** [comment]
@antonpaa , thank you!

After investigate this problem, i decide to remove "kwargs" from "run_keyword" method in python.
I have't published it to pypi yet, as i have some problem to access sikulixapi maven repo.
