### ISSUE TITLE
click region keyword not working

### ISSUE THREAD

**Issue by rohitJh** [rainmanwy/robotframework-SikuliLibrary#125]
I am new to Sikulib-Robot Framework. I am trying to click on a region using "Click Region" keyword. 

if i pass coordinates to keyword it gives error "java.lang.NullPointerException: null"
but if I find coordinate using "Get Image Coordinates" keyword and supply them to keyword  "Click Region" they works. 
Can you please tell my why this is happening and how can I make the first scenario work.
Thanks

**Comment by rainmanwy** [comment]
@rohitJh , could run test case with "-L trace", and attach the log.

**Comment by JerryXinhui** [comment]
@rainmanwy   hello, I have this issue too. Could you please help to have a  look?
Compared with  coordinates which get from Get Image Coordinates and I write directly, I find the coordinates I get from Get Image Coordinates is a "Ljava.lang.Object;@62261b6b" when I pass it to Click Region. 
I'm not able to attach the picture, so the log maybe hard to read, I'm sorry. And I'm look forward for your reply, because I really do need this keyword. Thanks a lot! 

 ${con} = SikuliLibrary . Get Image Coordinates test1.png
Documentation:	
Get Image Coordinates

Start / End / Elapsed:	20211119 09:23:22.365 / 20211119 09:23:22.554 / 00:00:00.189
09:23:22.365	TRACE	Arguments: [ 'test1.png' ]	
09:23:22.554	INFO	Params: [test1.png]	
09:23:22.554	TRACE	Return: [464, 201, 148, 20]	
09:23:22.554	INFO	${con} = [464, 201, 148, 20]	
00:00:00.000KEYWORD BuiltIn . Log ${con}
Documentation:	
Logs the given message with the given level.

Start / End / Elapsed:	20211119 09:23:22.555 / 20211119 09:23:22.555 / 00:00:00.000
09:23:22.555	TRACE	Arguments: [ [464, 201, 148, 20] ]	
09:23:22.555	INFO	[464, 201, 148, 20]	
09:23:22.555	TRACE	Return: None	
00:00:03.941KEYWORD SikuliLibrary . Click Region ${con}
Documentation:	
Click region

Start / End / Elapsed:	20211119 09:23:22.555 / 20211119 09:23:26.496 / 00:00:03.941
09:23:22.555	TRACE	Arguments: [ [464, 201, 148, 20] ]	
09:23:26.496	INFO	Params: [[Ljava.lang.Object;@64dcd79]	
09:23:26.496	DEBUG	Saved path: D:\01_code\python_code_pro\atecrt\BSCE\project\ATEC\Application\Logic\WIN10_XPF\sikuli_captured\sikuliximage-1637285002581.png	
09:23:26.496	INFO	
[log] CLICK on L[538,211]@S(0) (534 msec)	
09:23:26.496	DEBUG	Saved path: D:\01_code\python_code_pro\atecrt\BSCE\project\ATEC\Application\Logic\WIN10_XPF\sikuli_captured\sikuliximage-1637285006481.png	
09:23:26.496	INFO		
09:23:26.496	TRACE	Return: ''	
00:00:00.004KEYWORD SikuliLibrary . Click Region 464, 201, 148, 20
Documentation:	
Click region

Start / End / Elapsed:	20211119 09:23:26.497 / 20211119 09:23:26.501 / 00:00:00.004
09:23:26.497	TRACE	Arguments: [ '464, 201, 148, 20' ]	
09:23:26.501	INFO	Params: [464, 201, 148, 20]	
09:23:26.501	FAIL	java.lang.NullPointerException: null	
09:23:26.501	DEBUG	java.lang.NullPointerException
	at com.github.rainmanwy.robotframework.sikulilib.keywords.ScreenKeywords.clickRegion(ScreenKeywords.java:184)
	at com.github.rainmanwy.robotframework.sikulilib.keywords.ScreenKeywords.clickRegion(ScreenKeywords.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.robotframework.javalib.reflection.KeywordInvoker.invoke(KeywordInvoker.java:50)
	at org.robotframework.javalib.beans.annotation.AnnotationKeywordExtractor$1.execute(AnnotationKeywordExtractor.java:62)
	at org.robotframework.javalib.beans.annotation.AnnotationKeywordExtractor$2.execute(AnnotationKeywordExtractor.java:84)
	at org.robotframework.javalib.library.KeywordFactoryBasedLibrary.runKeyword(KeywordFactoryBasedLibrary.java:37)
	at org.robotframework.javalib.library.AnnotationLibrary.runKeyword(AnnotationLibrary.java:81)
	at com.github.rainmanwy.robotframework.sikulilib.SikuliLibrary.runKeyword(SikuliLibrary.java:40)
	at com.github.rainmanwy.robotframework.sikulilib.SikuliLibrary.runKeyword(SikuliLibrary.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.robotframework.remoteserver.library.DynamicApiRemoteLibrary.runKeyword(DynamicApiRemoteLibrary.java:65)
	at org.robotframework.remoteserver.servlet.ServerMethods.run_keyword(ServerMethods.java:90)
	at org.robotframework.remoteserver.servlet.ServerMethods.run_keyword(ServerMethods.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
	at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
	at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
	at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
	at org.apache.xmlrpc.webserver.XmlRpcServletServer.execute(XmlRpcServletServer.java:112)
	at org.apache.xmlrpc.webserver.XmlRpcServlet.doPost(XmlRpcServlet.java:196)
	at org.robotframework.remoteserver.servlet.RemoteServerServlet.doPost(RemoteServerServlet.java:122)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.robotframework.remoteserver.servlet.RemoteServerServlet.service(RemoteServerServlet.java:102)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:479)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:348)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:894)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:948)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:851)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
	at java.lang.Thread.run(Unknown Source)

**Comment by JerryXinhui** [comment]
@rainmanwy hello, I have this issue too. Could you please help to have a look?
Compared with coordinates which get from Get Image Coordinates and I write directly, I find the coordinates I get from Get Image Coordinates is a "Ljava.lang.Object;@62261b6b" when I pass it to Click Region.
I'm not able to attach the picture, so the log maybe hard to read, I'm sorry. And I'm look forward for your reply, because I really do need this keyword. Thanks a lot!

${con} = SikuliLibrary . Get Image Coordinates test1.png
Documentation:
Get Image Coordinates

Start / End / Elapsed: 20211119 09:23:22.365 / 20211119 09:23:22.554 / 00:00:00.189
09:23:22.365 TRACE Arguments: [ 'test1.png' ]
09:23:22.554 INFO Params: [test1.png]
09:23:22.554 TRACE Return: [464, 201, 148, 20]
09:23:22.554 INFO ${con} = [464, 201, 148, 20]
00:00:00.000KEYWORD BuiltIn . Log ${con}
Documentation:
Logs the given message with the given level.

Start / End / Elapsed: 20211119 09:23:22.555 / 20211119 09:23:22.555 / 00:00:00.000
09:23:22.555 TRACE Arguments: [ [464, 201, 148, 20] ]
09:23:22.555 INFO [464, 201, 148, 20]
09:23:22.555 TRACE Return: None
00:00:03.941KEYWORD SikuliLibrary . Click Region ${con}
Documentation:
Click region

Start / End / Elapsed: 20211119 09:23:22.555 / 20211119 09:23:26.496 / 00:00:03.941
09:23:22.555 TRACE Arguments: [ [464, 201, 148, 20] ]
09:23:26.496 INFO **Params: [[Ljava.lang.Object;@64dcd79]**
09:23:26.496 DEBUG Saved path: D:\sikuli_captured\sikuliximage-1637285002581.png
09:23:26.496 INFO
[log] CLICK on L[538,211]@s(0) (534 msec)
09:23:26.496 DEBUG Saved path: D:\sikuli_captured\sikuliximage-1637285006481.png
09:23:26.496 INFO
09:23:26.496 TRACE Return: ''
00:00:00.004KEYWORD SikuliLibrary . Click Region 464, 201, 148, 20
Documentation:
Click region

Start / End / Elapsed: 20211119 09:23:26.497 / 20211119 09:23:26.501 / 00:00:00.004
09:23:26.497 TRACE Arguments: [ '464, 201, 148, 20' ]
09:23:26.501 INFO Params: **[464, 201, 148, 20]**
09:23:26.501 FAIL java.lang.NullPointerException: null
09:23:26.501 DEBUG java.lang.NullPointerException
at com.github.rainmanwy.robotframework.sikulilib.keywords.ScreenKeywords.clickRegion(ScreenKeywords.java:184)
at com.github.rainmanwy.robotframework.sikulilib.keywords.ScreenKeywords.clickRegion(ScreenKeywords.java:208)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.robotframework.javalib.reflection.KeywordInvoker.invoke(KeywordInvoker.java:50)
at org.robotframework.javalib.beans.annotation.AnnotationKeywordExtractor$1.execute(AnnotationKeywordExtractor.java:62)
at org.robotframework.javalib.beans.annotation.AnnotationKeywordExtractor$2.execute(AnnotationKeywordExtractor.java:84)
at org.robotframework.javalib.library.KeywordFactoryBasedLibrary.runKeyword(KeywordFactoryBasedLibrary.java:37)
at org.robotframework.javalib.library.AnnotationLibrary.runKeyword(AnnotationLibrary.java:81)
at com.github.rainmanwy.robotframework.sikulilib.SikuliLibrary.runKeyword(SikuliLibrary.java:40)
at com.github.rainmanwy.robotframework.sikulilib.SikuliLibrary.runKeyword(SikuliLibrary.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.robotframework.remoteserver.library.DynamicApiRemoteLibrary.runKeyword(DynamicApiRemoteLibrary.java:65)
at org.robotframework.remoteserver.servlet.ServerMethods.run_keyword(ServerMethods.java:90)
at org.robotframework.remoteserver.servlet.ServerMethods.run_keyword(ServerMethods.java:154)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)
at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
at org.apache.xmlrpc.webserver.XmlRpcServletServer.execute(XmlRpcServletServer.java:112)
at org.apache.xmlrpc.webserver.XmlRpcServlet.doPost(XmlRpcServlet.java:196)
at org.robotframework.remoteserver.servlet.RemoteServerServlet.doPost(RemoteServerServlet.java:122)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
at org.robotframework.remoteserver.servlet.RemoteServerServlet.service(RemoteServerServlet.java:102)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:479)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
at org.eclipse.jetty.server.Server.handle(Server.java:348)
at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:894)
at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:948)
at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:851)
at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
at java.lang.Thread.run(Unknown Source)

**Comment by JerryXinhui** [comment]
After compare the log again, I come up an idea, and this can solve my problem. But I think it is better if  Click Region  [500,201,148,20] can work.  Thanks!
Workaround: 
${list}      create list     500  201  148    20
Click region      ${list}
(make the parameter as a list, seems need to trans the parameter to a  list in the background if we write like this: Click Region  [500,201,148,20] )

**Comment by rainmanwy** [comment]
I have updated some code, and tested with below:
    _${coor}   Click Text   Hello
    Click Region    ${coor}_

looks ok.
