### ISSUE TITLE
Upgading to use sikulixapi 1.1.1 fails to build

### ISSUE THREAD

**Issue by bkhouri** [rainmanwy/robotframework-SikuliLibrary#46]
I modified the `pom.xml` file to use sikulixapi version 1.1.1, but it failed to build as the dependency is missing.   Sikuli version 1.1.1 has been officially released (https://launchpad.net/sikuli/sikulix/1.1.1).  Is it possible to get the dependency on the sikulixapi JAR file fixed?

Can we get that api jar uploaded to maven central as soon as there is a new Sikuli X version available?

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building robotframework-SikuliLibrary 1.1.1
[INFO] ------------------------------------------------------------------------
Downloading: https://oss.sonatype.org/content/groups/public/com/sikulix/sikulixapi/1.1.1/sikulixapi-1.1.1.pom
Downloading: https://labs.consol.de/maven/repository/com/sikulix/sikulixapi/1.1.1/sikulixapi-1.1.1.pom
[WARNING] The POM for com.sikulix:sikulixapi:jar:1.1.1 is missing, no dependency information available
Downloading: https://oss.sonatype.org/content/groups/public/com/sikulix/sikulixapi/1.1.1/sikulixapi-1.1.1.jar
Downloading: https://labs.consol.de/maven/repository/com/sikulix/sikulixapi/1.1.1/sikulixapi-1.1.1.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.498 s
[INFO] Finished at: 2017-07-18T16:44:10-04:00
[INFO] Final Memory: 6M/17M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project robotframework-SikuliLibrary: Could not resolve dependencies for project com.github.rainmanwy.robotframework:robotframework-SikuliLibrary:jar:1.1.1: Could not find artifact com.sikulix:sikulixapi:jar:1.1.1 in com.sikulix (https://oss.sonatype.org/content/groups/public) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

Process finished with exit code 1
```

**Comment by rainmanwy** [comment]
you could have a try this version

http://mvnrepository.com/artifact/com.sikulix/sikulixapi/1.1.999



获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bkhouri** [comment]
That is nothing a valid version.                                                                                                                                                                          Sent from my BlackBerry - the most secure mobile device                                                                                                                                                                            From: notifications@github.comSent: July 18, 2017 5:40 PMTo: robotframework-SikuliLibrary@noreply.github.comReply-to: reply@reply.github.comCc: bassam.khouri@gmail.com; author@noreply.github.comSubject: Re: [rainmanwy/robotframework-SikuliLibrary] Upgading to use sikulixapi 1.1.1 fails to build (#46)  you could have a try this version



http://mvnrepository.com/artifact/com.sikulix/sikulixapi/1.1.999







获取 Outlook for Android<https://aka.ms/ghei36>



________________________________

**Comment by rainmanwy** [comment]
@bkhouri , i found 1.1.1 version has been uploaded to maven repository. [1.1.1](http://mvnrepository.com/artifact/com.sikulix/sikulixapi/1.1.1)

**Comment by RaiMan** [comment]
... and please be aware of this new info:
[How to use with Maven](https://github.com/RaiMan/SikuliX-2014/wiki/How-to-use-with-Maven)

**Comment by rainmanwy** [comment]
thank you, raimund(sometimes your and my name make people confused:)).

I found 1.1.1 has larger size(SikuliLibrary.jar changed from 15M to 30M. some tesseract files are included. are there some changes with ocr?

获取 Outlook for Android<https://aka.ms/ghei36>

**Comment by RaiMan** [comment]
sometimes your and my name make people confused:)

… as long as nothing else makes them headaches ;-)

tessdata files included:
Since Tesseract has moved to GitHub with a completely revised structure, I wanted to reduce the problems with missing tessdata folder in all cases (setup and Maven) and the easiest ;-) solution was to simply bundle the tessdata stuff.
No changes to the OCR/text features - still the same since 5 years :-(
… but I revised the faq on how to switch to a different language for OCR (https://answers.launchpad.net/sikuli/+faq/2709)

all the best.

Raimund aka RaiMan

Joke: I can change my name to RaiMan-why-not-RainMan (which is the confusion, that I see mostly)

Am 08.11.2017 um 07:53 schrieb Rainmanwy <notifications@github.com<mailto:notifications@github.com>>:

thank you, raimund(sometimes your and my name make people confused:)).

I found 1.1.1 has larger size(SikuliLibrary.jar changed from 15M to 30M. some tesseract files are included. are there some changes with ocr?

获取 Outlook for Android<https://aka.ms/ghei36>

**Comment by rainmanwy** [comment]
@RaiMan 
Rainman is my nickname which come from movie "Rainman":).
Could you give me your private email address, i'd like to know more about sikuli.
Actually i have noticed this project in 2009, and i remember that it was developed by MIT, right?

**Comment by RaiMan** [comment]
@rainmanwy 
use the mail at my GitHub home (https://github.com/RaiMan).

Movie Rainman - yes I know ;-)

My nickname comes from my 2 first names RAImund and MANfred and people reading inattentively often think they have read RainMan.

Yes, MIT is right: info at sikulix.com:
Sikuli was started somewhen in 2009 as an open-source research project at the User Interface Design Group at MIT by Tsung-Hsiang Chang and Tom Yeh.
Both left the project at Sikuli-X-1.0rc3 during 2012, when I decided to take over development and support and name it SikuliX.

BTW: Tsung-Hsiang chose GodsEye as his nickname. He is completely out of that. Tom Yeh is still active with a Sikuli variant called Sikuli Slides (https://github.com/sikuli/sikuli-slides) working at Colorado university.

**Comment by rainmanwy** [comment]
@RaiMan 

Thank you for these information. Seems this is not right place to continue the discussion:). I have send the mail to you.

**Comment by HelioGuilherme66** [comment]
@rainmanwy Let me hijack this Issue because it is related.
I could not build the package because it is complaining to not find python3. (I still use python2.7).
Could you please prepare a new release? Thanks.
-This is the final output:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.916 s
[INFO] Finished at: 2018-08-08T15:06:03+01:00
[INFO] Final Memory: 69M/167M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run (dist) on project robotframework-SikuliLibrary: An Ant BuildException has occured: Execute failed: java.io.IOException: Cannot run program "python3" (in directory "C:\github\robotframework-SikuliLibrary\target\src"): CreateProcess error=2, O sistema nÒo conseguiu localizar o ficheiro especificado -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run (dist) on project robotframework-SikuliLibrary: An Ant BuildException has occured: Execute failed: java.io.IOException: Cannot run program "python3" (in directory "C:\github\robotframework-SikuliLibrary\target\src"): CreateProcess error=2, O sistema nÒo conseguiu localizar o ficheiro especificado
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: An Ant BuildException has occured: Execute failed: java.io.IOException: Cannot run program "python3" (in directory "C:\github\robotframework-SikuliLibrary\target\src"): CreateProcess error=2, O sistema nÒo conseguiu localizar o ficheiro especificado
        at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:283)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: C:\github\robotframework-SikuliLibrary\target\antrun\build-main.xml:7: Execute failed: java.io.IOException: Cannot run program "python3" (in directory "C:\github\robotframework-SikuliLibrary\target\src"): CreateProcess error=2, O sistema nÒo conseguiu localizar o ficheiro especificado
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:679)
        at org.apache.tools.ant.taskdefs.ExecTask.execute(ExecTask.java:502)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
        at org.apache.tools.ant.Task.perform(Task.java:348)
        at org.apache.tools.ant.Target.execute(Target.java:390)
        at org.apache.tools.ant.Target.performTasks(Target.java:411)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1397)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1366)
        at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:270)
        ... 22 more
Caused by: java.io.IOException: Cannot run program "python3" (in directory "C:\github\robotframework-SikuliLibrary\target\src"): CreateProcess error=2, O sistema nÒo conseguiu localizar o ficheiro especificado
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at java.lang.Runtime.exec(Runtime.java:617)
        at org.apache.tools.ant.taskdefs.Execute$Java13CommandLauncher.exec(Execute.java:827)
        at org.apache.tools.ant.taskdefs.Execute.launch(Execute.java:445)
        at org.apache.tools.ant.taskdefs.Execute.execute(Execute.java:459)
        at org.apache.tools.ant.taskdefs.ExecTask.runExecute(ExecTask.java:635)
        at org.apache.tools.ant.taskdefs.ExecTask.runExec(ExecTask.java:676)
        ... 35 more
Caused by: java.io.IOException: CreateProcess error=2, O sistema nÒo conseguiu localizar o ficheiro especificado
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:385)
        at java.lang.ProcessImpl.start(ProcessImpl.java:136)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        ... 41 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by rainmanwy** [comment]
@HelioGuilherme66 , 
You may replace "python3" to "python" in pom.xml

`
<exec dir="target/src" executable="python3" failonerror="true">
	<arg line="-m SikuliLibrary.__init__" />
</exec>
`
I am using Linux, and there are python2 and python3 in my OS.
It may be configured as a parameter, and user could input it when using "mvn package" command.

Do you have any suggestion about it?

**Comment by HelioGuilherme66** [comment]
Thank you, it worked.

There is no need to do that configuration. Regular users just want to have the package to install.
Documentation is enough :).

(However I would like to have package ready to install in the Releases section)

**Comment by rainmanwy** [comment]
Thanks @HelioGuilherme66 , I will update the documentation later.

About the release section, as sikulixapi is OS depended(Linux, Windows, Mac), currectly i could only package the jar for Linux. I haven't checked whether could package jars for different OS on my Linux.

@RaiMan , do you have any suggestion about it?

I found there are profiles for each OS
`
<profile>
<id>Windows</id>
<activation>
<os>
<family>windows</family>
</os>
</activation>
<properties>
<sikulix.libs>sikulixlibswin</sikulix.libs>
</properties>
</profile>
<profile>
<id>Unix</id>
<activation>
<os>
<family>unix</family>
</os>
</activation>
<properties>
<sikulix.libs>sikulixlibslux</sikulix.libs>
</properties>
</profile>
<profile>
<id>Mac</id>
<activation>
<os>
<family>mac</family>
</os>
</activation>
<properties>
<sikulix.libs>sikulixlibsmac</sikulix.libs>
</properties>
</profile>
`

Whether i could configured it in my own pom, and package jar for windows on my Linux?

**Comment by RaiMan** [comment]
@rainmanwy 
The easiest way, to get a sikulixapi.jar for another world:
run a setup from a commandline according to https://answers.launchpad.net/sikuli/+faq/2609

e.g. for Windows: `java -jar sikulixsetup-1.1.3.jar options 2 4.1 notest`

This sikulixapi.jar could then be used in further packaging processing.

... so you could even produce a "one-for-all" version (rather fat though ;-)

**Comment by rainmanwy** [comment]
@RaiMan , Thanks!

I have updated pom.xml, and add profiles and dependency with "sikulix.libs".
Looks good, and i could package jar file for windows on my Linux:)

**Comment by HelioGuilherme66** [comment]
@rainmanwy On Windows with Python 3.6.5 build fails. Cannot create keywords.py. I successfully created keywords.py with Python 2.7.13.
(I wonder if you could be available for online chat at channel #sikulix_integration on our [Slack](https://robotframework-slack-invite.herokuapp.com/))

This is the failed build output:
```
[INFO] --- maven-antrun-plugin:1.6:run (dist) @ robotframework-SikuliLibrary ---
[WARNING] Parameter tasks is deprecated, use target instead
[INFO] Executing tasks

main:
     [echo] unzip package
    [unzip] Expanding: C:\github\robotframework-SikuliLibrary\target\SikuliLibrary.zip into C:\github\robotframework-SikuliLibrary\target\src
     [echo] generate keywords.py
     [exec] Free TCP port is: 64124
     [exec] Start sikuli java process on port 64124
     [exec] error........Start sikuli java process failed!
     [exec] Free TCP port is: 64169
     [exec] Start sikuli java process on port 64169
     [exec] error........Start sikuli java process failed!
     [exec] Free TCP port is: 64211
     [exec] Start sikuli java process on port 64211
     [exec] error........Start sikuli java process failed!
     [exec] Free TCP port is: 64269
     [exec] Start sikuli java process on port 64269
     [exec] error........Start sikuli java process failed!
     [exec] Free TCP port is: 64303
     [exec] Start sikuli java process on port 64303
     [exec] Traceback (most recent call last):
     [exec]   File "c:\python36\lib\runpy.py", line 193, in _run_module_as_main
     [exec]     "__main__", mod_spec)
     [exec]   File "c:\python36\lib\runpy.py", line 85, in _run_code
     [exec]     exec(code, run_globals)
     [exec]   File "C:\github\robotframework-SikuliLibrary\target\src\SikuliLibrary\__init__.py", line 15, in <module>
     [exec]     main()
     [exec]   File "C:\github\robotframework-SikuliLibrary\target\src\SikuliLibrary\__init__.py", line 11, in main
     [exec]     lib = SikuliLibrary(mode='CREATE')
     [exec]   File "C:\github\robotframework-SikuliLibrary\target\src\SikuliLibrary\sikuli.py", line 61, in __init__
     [exec]     self._create_keywords_file()
     [exec]   File "C:\github\robotframework-SikuliLibrary\target\src\SikuliLibrary\sikuli.py", line 97, in _create_keywords_file
     [exec]     self.start_sikuli_process()
     [exec]   File "C:\github\robotframework-SikuliLibrary\target\src\SikuliLibrary\sikuli.py", line 92, in start_sikuli_process
     [exec]     raise RuntimeError('Start sikuli java process failed!')
     [exec] RuntimeError: Start sikuli java process failed!
     [exec] error........Start sikuli java process failed!
     [exec] Free TCP port is: 64336
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:16 min
[INFO] Finished at: 2018-08-14T12:16:46+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.6:run (dist) on project robotframework-SikuliLibrary: An Ant BuildException has occured: exec returned: 1 -> [Help 1]
```

**Comment by rainmanwy** [comment]
@HelioGuilherme66 , I am sorry i could not access "Slack" from my office network.
I have modified setup.py, so that you could using python2.7 to package py2 py3 wheel.
the python code in this project is py2&py3 compatible, so do not need to create different release.

For this error, whether py3 in your env is blocked by windows firewall?
After sikuli jar is started, python code will check TCP port is accessible.

`
def _wait_process_started(self):
        url = "http://127.0.0.1:%s/" % str(self.port)
        currentTime = startedTime = time.time()
        started = False
        while (currentTime - startedTime) < self.timeout:
            try:
                urlopen(url).read()
            except Exception:
                currentTime = time.time()
                time.sleep(1.0)
                continue
            started = True
            break
        if not started:
            raise RuntimeError('Start sikuli java process failed!')
`

As jar and python code is same for py2 and py3, so maybe the error is related with your environment.
