### ISSUE TITLE
Unable to build with Maven

### ISSUE THREAD

**Issue by abioneperhobby** [rainmanwy/robotframework-SikuliLibrary#47]
C:\src\robotframework-SikuliLibrary>mvn install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building robotframework-SikuliLibrary 1.0
[INFO] ------------------------------------------------------------------------
Downloading: http://pz-ci:8081/artifactory/remote-repos/jxgrabkey/jxgrabkey/1.0/jxgrabkey-1.0.pom
[WARNING] The POM for jxgrabkey:jxgrabkey:jar:1.0 is missing, no dependency information available
Downloading: http://pz-ci:8081/artifactory/remote-repos/jxgrabkey/jxgrabkey/1.0/jxgrabkey-1.0.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.955 s
[INFO] Finished at: 2017-09-26T16:38:43+02:00
[INFO] Final Memory: 10M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project robotframework-SikuliLibrary: Could not resolve dependencies for project com.github.rainmanwy.robotframework:robotframework-SikuliLibrary:jar:1.0: Could not find artifact jxgrabkey:jxgrabkey:jar:1.0 in remote-repos (http://pz-ci:8081/artifactory/remote-repos) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

C:\src\robotframework-SikuliLibrary>

**Comment by rainmanwy** [comment]
@abioneperhobby , guess it is related with your maven setting configuration.
jxgrabkey is not in maven center repository.
The repo is configured in pom.xml

`<repository>
      
			<name>jxgrabkey</name>
			<id>jxgrabkey</id>
			<url>https://labs.consol.de/maven/repository/</url>
			
			<releases>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			</releases>
			<snapshots>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			</snapshots>
		</repository>
	</repositories>`

not sure why maven not get from that repo in your env. But you may check maven setting xml file.

**Comment by abioneperhobby** [comment]
@rainmanwy thanks
i'm not skilled with maven,
but i used time ago because i'm not able to install robotframework-sikulilibrary by pip because it using execFile, but execFile is python 2 related. Due execFile should be removed with this commit (https://github.com/rainmanwy/robotframework-SikuliLibrary/commit/274e12ec7634e0eba16b1b288e5b36fdd303ac7a) i think the version i install with pip is not the last.

```
C:\Users\andrea.bisello>pip3 install robotframework-sikulilibrary
Collecting robotframework-sikulilibrary
  Using cached robotframework-SikuliLibrary-0.1.5.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ANDREA~1.BIS\AppData\Local\Temp\pip-build-71ux3n22\robotframework-sikulilibrary\setup.py", line 10, in <module>
        execfile(join(dirname(abspath(__file__)), 'target', 'src', 'SikuliLibrary', 'version.py'))
    NameError: name 'execfile' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ANDREA~1.BIS\AppData\Local\Temp\pip-build-71ux3n22\robotframework-sikulilibrary\
```

THEN i tried to build with maven. in order to build with maven i cloned the source and i run "mvn install". 

the maven setting xml file is 

```
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
	<groupId>com.github.rainmanwy.robotframework</groupId>
	<artifactId>robotframework-SikuliLibrary</artifactId>
	<version>1.0</version>
	<packaging>jar</packaging>
	<name>robotframework-SikuliLibrary</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

    <repositories>
		<repository>
      <!-- OSSRH: com.sikulix -->
			<name>com.sikulix</name>
			<id>com.sikulix</id>
			<url>https://oss.sonatype.org/content/groups/public</url>
			<!--layout>default</layout-->
			<releases>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			</releases>
			<snapshots>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			</snapshots>
		</repository>
        <repository>
      <!-- OSSRH: com.sikulix -->
			<name>jxgrabkey</name>
			<id>jxgrabkey</id>
			<url>https://labs.consol.de/maven/repository/</url>
			<!--layout>default</layout-->
			<releases>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			</releases>
			<snapshots>
				<enabled>true</enabled>
				<updatePolicy>always</updatePolicy>
			</snapshots>
		</repository>
	</repositories>
    
    
	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.8</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.sikulix</groupId>
			<artifactId>sikulixapi</artifactId>
			<version>1.1.0</version>
		</dependency>
        <!--dependency>
            <groupId>org.robotframework</groupId>
            <artifactId>javalib-core</artifactId>
            <version>1.2.1</version>
        </dependency-->
        <dependency>
            <groupId>com.github.ombre42</groupId>
            <artifactId>jrobotremoteserver</artifactId>
            <version>3.0</version>
        </dependency>


	</dependencies>

	<build>
        <sourceDirectory>src/java</sourceDirectory>
		<plugins>

			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.1</version>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
				</configuration>
			</plugin>

			<!--plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>2.4</version>
				<configuration>
					<archive>
						<manifest>
							<mainClass>com.github.rainmanwy.robotframework.sikulilib.SikuliLibrary</mainClass>
							<addClasspath>true</addClasspath>
							<classpathPrefix>dependency-jars/</classpathPrefix>
						</manifest>
					</archive>
					<finalName>SikuliLibrary</finalName>
				</configuration>
			</plugin-->
			
			
            <!--plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <version>2.5.1</version>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <includeScope>runtime</includeScope>
                            <outputDirectory>${project.build.directory}/dependency-jars/
                            </outputDirectory>

                        </configuration>
                    </execution>
                </executions>
            </plugin-->

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>2.6</version>
				<configuration>
					<!--descriptor>package.xml</descriptor-->
					<finalName>SikuliLibrary</finalName>
                    <appendAssemblyId>false</appendAssemblyId>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
					<archive>
						<manifest>
							<mainClass>com.github.rainmanwy.robotframework.sikulilib.SikuliLibrary</mainClass>
							<addClasspath>true</addClasspath>
						</manifest>
					</archive>
				</configuration>
				<executions>
					<execution>
						<id>make-assembly</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
                    <execution>
						<id>dist</id>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
                        <configuration>
                            <descriptors>
                                <descriptor>assembly.xml</descriptor>
                            </descriptors>
                        </configuration>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-antrun-plugin</artifactId>
				<version>1.6</version>
				<executions>
					<execution>
						<id>dist</id>
						<phase>package</phase>
						<configuration>
							<tasks>
								<echo message="unzip package" />
								<unzip src="target/SikuliLibrary.zip" dest="target/src" />
								<!--<unzip src="output/inner.zip" dest="output" />-->
								<!--<unzip dest="output">-->
								  <!--<fileset dir="archives">-->
									<!--<include name="prefix*.zip" />-->
								  <!--</fileset>-->
								<!--</unzip>-->
							</tasks>
						</configuration>
						<goals>
							<goal>run</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>
</project>
```

and this is my maven
```
C:\Users\andrea.bisello>mvn -v
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: C:\apache-maven-3.5.0-bin\apache-maven-3.5.0\bin\..
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: C:\Program Files\Java\jre1.8.0_144
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by rainmanwy** [comment]
You may check your settings.xml file. It may in "C:\apache-maven-3.5.0-bin\apache-maven-3.5.0\conf", or in m2 folder
[settings.xml](http://maven.apache.org/settings.html)

**Comment by abioneperhobby** [comment]
due on a fresh windows 10 installation it works, there is something wrong with my actual machine.
i'll close the issue.
