### ISSUE TITLE
'Start Sikuli java process failed!

### ISSUE THREAD

**Issue by prasanthsiva** [rainmanwy/robotframework-SikuliLibrary#66]
Hi Team,

Frequently am facing the issue when we run in Jenkins Pipeline. Please find the below error and help us in this,

![error](https://user-images.githubusercontent.com/16998674/38971741-29d59cae-43ba-11e8-9334-a4cb2e197ec4.png)

0180418 17:03:47.197 	ERROR 	Error in file '/home/design/wma/nonNE/nonnewma_script/CSCF_A1_Add_CSCF_node.txt': Initializing test library 'SikuliLibrary' with no arguments failed: Start sikuli java process failed!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SikuliLibrary/sikuli.py", line 54, in __init__
    self.start_sikuli_process(port)
  File "/usr/local/lib/python2.7/dist-packages/SikuliLibrary/sikuli.py", line 92, in start_sikuli_process
    raise RuntimeError('Start sikuli java process failed!') 	
20180418 17:04:07.268 	ERROR 	Error in file '/home/design/wma/wma_common_keywords.txt': Initializing test library 'SikuliLibrary' with no arguments failed: Start sikuli java process failed!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SikuliLibrary/sikuli.py", line 54, in __init__
    self.start_sikuli_process(port)
  File "/usr/local/lib/python2.7/dist-packages/SikuliLibrary/sikuli.py", line 92, in start_sikuli_process
    raise RuntimeError('Start sikuli java process failed!') 	
20180418 17:04:27.322 	ERROR 	Error in file '/home/design/wma/nonNE/nonnewma_script/CSCF_A2_Modify_CSCF_node.txt': Initializing test library 'SikuliLibrary' with no arguments failed: Start sikuli java process failed!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/SikuliLibrary/sikuli.py", line 54, in __init__
    self.start_sikuli_process(port)
  File "/usr/local/lib/python2.7/dist-packages/SikuliLibrary/sikuli.py", line 92, in start_sikuli_process
    raise RuntimeError('Start sikuli java process failed!')

**Comment by rainmanwy** [comment]
@prasanthsiva , how did you install this lib. From pypi, or packaged it locally.
The version from pypi only support windows. So if you are using linux, you have to package it yourself.
