### ISSUE TITLE
Getting "FAILED SikuliLibrary Initializing test library 'SikuliLibrary' with no arguments failed: Sikuli jar package should be exist in lib folder"

### ISSUE THREAD

**Issue by deepakg4all** [rainmanwy/robotframework-SikuliLibrary#69]
Hi,
I am evaluating robot+sikuli but I am getting below error though I set Java_home,python_home and define all require sikuli libraries in env variable. Also, http://127.0.0.1:10000/ working properly. 

**Error via RIDE:** 
FAILED SikuliLibrary Initializing test library 'SikuliLibrary' with no arguments failed: Sikuli jar package should be exist in lib folder
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 184, in _get_instance
    return libcode(*self.positional_args, **self.named_args)
  File "C:\Python27\lib\site-packages\SikuliLibrary\sikuli.py", line 54, in __init__
    self.start_sikuli_process(port)
  File "C:\Python27\lib\site-packages\SikuliLibrary\sikuli.py", line 81, in start_sikuli_process
    self._start_sikuli_java_process()
  File "C:\Python27\lib\site-packages\SikuliLibrary\sikuli.py", line 153, in _start_sikuli_java_process
    raise Exception('Sikuli jar package should be exist in lib folder')

**Sample Code**
*** Settings ***
Suite Setup       Start Sikuli Process
Suite Teardown    Stop Remote Server
Library           SikuliLibrary    mode=new

*** Test Cases ***
New Mode
    Add Image Path    C:\\Users\\test\\Desktop\\sikuli.sikuli
    Click    click.png

**Env Details :**
OS : Window 10 
Python Version: 2.7 (32 bit)
Robot Framework 3.0.2 (Python 2.7.13 on win32)
Robot-SikuliLibrary : 1.0.1

Can you please help me to move ahead? Thanks in Advance.

**Comment by rainmanwy** [comment]
Could you confirm that "SikuliLibrary.jar" is existed in "C:\Python27\lib\site-packages\SikuliLibrary\lib".
`jarList = glob.glob(libFolder + os.sep + '*.jar')
if len(jarList) != 1:
        raise Exception('Sikuli jar package should be exist in lib folder')
`
python library will check "SikuliLibrary/lib" folder, and make sure there is only one jar file in the folder.

**Comment by deepakg4all** [comment]
Spot On, I see multiple Jars in that folder. I thought additional jar's won't create any issue.  After deleting additional jars it worked like a charm. Thank man!

**Comment by pb9288** [comment]
I am using Sikuli+robotframework and currently I am unable to execute this small piece of code.

**1. Details**
OS: Windows 7
python: 2.7.14
pip: 19.0.3
robotframework: 3.1.1
robotframework-SikuliLibrary: 1.0.2
setuptools: 28.8.0

**2. Error:**
==============================================================================
Notepad :: Sikuli Demo
==============================================================================
Open Notepad                                                          | FAIL |
No keyword with name 'Open Application' found.

Also teardown failed:
Several failures occurred:

**3. Build jar file**
I also tried to build the jar file.
Now I have total of 3 SikuliLibrary.jar file in c:\Python27
But I am still stuck with same error when I run the Test.

.
.
.
SikuliLibrary.sikuli: module references __file__
creating 'dist\robotframework_SikuliLibrary-1.0.2-py2.7.egg' and adding 'build\bdist.win32\egg' to it
removing 'build\bdist.win32\egg' (and everything under it)
Processing robotframework_SikuliLibrary-1.0.2-py2.7.egg
removing 'c:\python27\lib\site-packages\robotframework_SikuliLibrary-1.0.2-py2.7.egg' (and everything under it)
creating c:\python27\lib\site-packages\robotframework_SikuliLibrary-1.0.2-py2.7.egg
Extracting robotframework_SikuliLibrary-1.0.2-py2.7.egg to c:\python27\lib\site-packages
robotframework-SikuliLibrary 1.0.2 is already the active version in easy-install.pth

Installed c:\python27\lib\site-packages\robotframework_sikulilibrary-1.0.2-py2.7.egg
Processing dependencies for robotframework-SikuliLibrary==1.0.2
Finished processing dependencies for robotframework-SikuliLibrary==1.0.2_


**4. Test.robot**
*** Settings ***
Documentation  Sikuli Demo
Library       SikuliLibrary

*** Variables ***
${PATH_EXE} =    C:\\windows\\system32\\notepad.exe

*** Test Cases ***
Open Notepad
    Open Notepad
    
*** Keywords ***
Open Notepad
    Open Application  ${PATH_EXE}
    Double Click    notepad_title.png

**5**. 
I was able to run some selenium code.

@rainmanwy 
Can you help me find out what is missing in the prerequisites?
Thanks in advance.

**Comment by mayribeirofernandes** [comment]
I was having this same problem, I checked the .jar in the folder, but it was no use, so I did it to work:
1 - I made sure that JAVA JRE 64bits was installed;
2 - I searched the library in the python sikuli folder on my machine (in my case it was `c:\users\mayara.fernandes\appdata\local\programs\python\python37-32\lib\site-packages\SikuliLibrary\lib`) and put it not to be read only;
3 - Finally I changed the library code:
In the library source code, in the file: `C:\Users\mayara.fernandes\AppData\Local\Programas\Python\Python37-32\Lib\site-packages\SikuliLibrary\sikuli.py` i opened it and changed the function named `_start_sikuli_java_process`,
i changed: `jarList = glob.glob (libFolder + os.sep + '* .jar')`
to: `jarList = glob.glob (libFolder + os.sep + 'SikuliLibrary.jar')`

**Comment by RaviGee** [comment]
> I was having this same problem, I checked the .jar in the folder, but it was no use, so I did it to work:
> 1 - I made sure that JAVA JRE 64bits was installed;
> 2 - I searched the library in the python sikuli folder on my machine (in my case it was `c:\users\mayara.fernandes\appdata\local\programs\python\python37-32\lib\site-packages\SikuliLibrary\lib`) and put it not to be read only;
> 3 - Finally I changed the library code:
> In the library source code, in the file: `C:\Users\mayara.fernandes\AppData\Local\Programas\Python\Python37-32\Lib\site-packages\SikuliLibrary\sikuli.py` i opened it and changed the function named `_start_sikuli_java_process`,
> i changed: `jarList = glob.glob (libFolder + os.sep + '* .jar')`
> to: `jarList = glob.glob (libFolder + os.sep + 'SikuliLibrary.jar')`

Thank you @mayribeirofernandes I was stuck with same issue and your solution worked for me. 👍
