### ISSUE TITLE
run sikuli on mac:Connection refused

### ISSUE THREAD

**Issue by crown00000** [rainmanwy/robotframework-SikuliLibrary#77]
I want run sikili on mac, but not work
[echo] unzip package
    [unzip] Expanding: /Users/JRFinCloudBuild/robotframework-SikuliLibrary/target/SikuliLibrary.zip into /Users/JRFinCloudBuild/robotframework-SikuliLibrary/target/src
     [echo] generate keywords.py
     [exec] Free TCP port is: 49940
     [exec] Start sikuli java process on port 49940
     [exec] Sikuli java process is started
     [exec] Test get_keyword_names failed! Connecting remote server at http://127.0.0.1:49940/ failed: [Errno 61] Connection refused
     [exec] Traceback (most recent call last):
     [exec]   File "/Users/JRFinCloudBuild/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
     [exec]     "__main__", mod_spec)
     [exec]   File "/Users/JRFinCloudBuild/.pyenv/versions/3.6.1/lib/python3.6/runpy.py", line 85, in _run_code
     [exec]     exec(code, run_globals)
     [exec]   File "/Users/JRFinCloudBuild/robotframework-SikuliLibrary/target/src/SikuliLibrary/__init__.py", line 15, in <module>
     [exec]     main()
     [exec]   File "/Users/JRFinCloudBuild/robotframework-SikuliLibrary/target/src/SikuliLibrary/__init__.py", line 11, in main
     [exec]     lib = SikuliLibrary(mode='CREATE')
     [exec]   File "/Users/JRFinCloudBuild/robotframework-SikuliLibrary/target/src/SikuliLibrary/sikuli.py", line 61, in __init__
     [exec]     self._create_keywords_file()
     [exec]   File "/Users/JRFinCloudBuild/robotframework-SikuliLibrary/target/src/SikuliLibrary/sikuli.py", line 97, in _create_keywords_file
     [exec]     self.start_sikuli_process()
     [exec]   File "/Users/JRFinCloudBuild/robotframework-SikuliLibrary/target/src/SikuliLibrary/sikuli.py", line 93, in start_sikuli_process
     [exec]     self.remote = self._connect_remote_library()
     [exec]   File "/Users/JRFinCloudBuild/robotframework-SikuliLibrary/target/src/SikuliLibrary/sikuli.py", line 204, in _connect_remote_library
     [exec]     self._test_get_keyword_names(remote)
     [exec]   File "/Users/JRFinCloudBuild/robotframework-SikuliLibrary/target/src/SikuliLibrary/sikuli.py", line 221, in _test_get_keyword_names
     [exec]     raise RuntimeError('Failed to get_keyword_names!')
     [exec] RuntimeError: Failed to get_keyword_names!

**Comment by rainmanwy** [comment]
@crown00000 , so you use maven to install this library yourself?
How about the jdk version you are using?

Could you attach sikuli log here?
