### ISSUE TITLE
Failed to import SikuliLibrary with RobotFramework

### ISSUE THREAD

**Issue by YiQiSun-Uniques** [rainmanwy/robotframework-SikuliLibrary#81]
I got an error when I added SikuliLibrary to RobotFramework : 
Initializing test library 'SikuliLibrary' with no arguments failed: Failed to get_keyword_names!
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robotide\lib\robot\running\testlibraries.py", line 184, in _get_instance
    return libcode(*self.positional_args, **self.named_args)
  File "C:\Python27\lib\site-packages\SikuliLibrary\sikuli.py", line 54, in __init__
    self.start_sikuli_process(port)
  File "C:\Python27\lib\site-packages\SikuliLibrary\sikuli.py", line 93, in start_sikuli_process
    self.remote = self._connect_remote_library()
  File "C:\Python27\lib\site-packages\SikuliLibrary\sikuli.py", line 204, in _connect_remote_library
    self._test_get_keyword_names(remote)
  File "C:\Python27\lib\site-packages\SikuliLibrary\sikuli.py", line 221, in _test_get_keyword_names
    raise RuntimeError('Failed to get_keyword_names!')
  File "C:\Python27\lib\site-packages\robotide\spec\librarymanager.py", line 81, in _fetch_keywords 

what I did is : use "pip install robotframework-SikuliLibrary" to install SikuliLibrary and than added it to my test case, but it does not work. I tried multi times and always failed. Do I need extra steps? Thanks

Python 2.7.14
Win10
java version "9.0.1"

**Comment by rainmanwy** [comment]
Could you attach sikuli log here.

**Comment by YiQiSun-Uniques** [comment]
Thank you for your response!
I fixed the issue by using Java 1.8. BTW Can you help me to set the specific path for sikuli log? The log is saved on my desktop, It annoyed me .Thanks~

**Comment by rainmanwy** [comment]
You may check the doc [disable java process log file ](https://github.com/rainmanwy/robotframework-SikuliLibrary#disable-java-process-log-file)
