### ISSUE TITLE
input text encoding issue

### ISSUE THREAD

**Issue by KEYSERQA** [rainmanwy/robotframework-SikuliLibrary#83]
Hello All,
I have an encoding issue in text field after using input text Keyword (robotframework-SikuliLibrary).
My test
![image](https://user-images.githubusercontent.com/45819102/49945571-7fd26800-feed-11e8-8df5-10a5b3bc3f0d.png)

result
![image](https://user-images.githubusercontent.com/45819102/49945623-9aa4dc80-feed-11e8-8f56-a5efcbad47d4.png)

As you can I get "USÀÀÀÀ"ÈÈÈ" when expected result should be "US00003777"

robotframework==3.1
robotframework-SikuliLibrary==1.0.3
Python 3.6.7
windows 7

Help will be really appreciate
Thank you

**Comment by rainmanwy** [comment]
@KEYSERQA , could you have a try "Paste Text" keyword.
This problem only related with this UI component or it is related with your Operating System?

**Comment by KEYSERQA** [comment]
Hello @rainmanwy 
Thank for you reply. With "Past Text "  I don't have encoding problem problem. 
![image](https://user-images.githubusercontent.com/45819102/49992217-b3f86800-ff83-11e8-8fdf-d75d86a7a9a4.png)

But it raised en exception
![image](https://user-images.githubusercontent.com/45819102/49992453-6cbea700-ff84-11e8-8077-e93adbf31ca7.png)

com.github.rainmanwy.robotframework.sikulilib.exceptions.ScreenOperationException: Paste text failed
	at com.github.rainmanwy.robotframework.sikulilib.keywords.ScreenKeywords.pasteText(ScreenKeywords.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.robotframework.javalib.reflection.KeywordInvoker.invoke(KeywordInvoker.java:50)
	at org.robotframework.javalib.beans.annotation.AnnotationKeywordExtractor$1.execute(AnnotationKeywordExtractor.java:62)
	at org.robotframework.javalib.library.KeywordFactoryBasedLibrary.runKeyword(KeywordFactoryBasedLibrary.java:37)
	at org.robotframework.javalib.library.AnnotationLibrary.runKeyword(AnnotationLibrary.java:81)
	at com.github.rainmanwy.robotframework.sikulilib.SikuliLibrary.runKeyword(SikuliLibrary.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.robotframework.remoteserver.library.DynamicApiRemoteLibrary.runKeyword(DynamicApiRemoteLibrary.java:65)
	at org.robotframework.remoteserver.servlet.ServerMethods.run_keyword(ServerMethods.java:90)
	at org.robotframework.remoteserver.servlet.ServerMethods.run_keyword(ServerMethods.java:154)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.invoke(ReflectiveXmlRpcHandler.java:115)
	at org.apache.xmlrpc.server.ReflectiveXmlRpcHandler.execute(ReflectiveXmlRpcHandler.java:106)
	at org.apache.xmlrpc.server.XmlRpcServerWorker.execute(XmlRpcServerWorker.java:46)
	at org.apache.xmlrpc.server.XmlRpcServer.execute(XmlRpcServer.java:86)
	at org.apache.xmlrpc.server.XmlRpcStreamServer.execute(XmlRpcStreamServer.java:200)
	at org.apache.xmlrpc.webserver.XmlRpcServletServer.execute(XmlRpcServletServer.java:112)
	at org.apache.xmlrpc.webserver.XmlRpcServlet.doPost(XmlRpcServlet.java:196)
	at org.robotframework.remoteserver.servlet.RemoteServerServlet.doPost(RemoteServerServlet.java:122)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.robotframework.remoteserver.servlet.RemoteServerServlet.service(RemoteServerServlet.java:102)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:479)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
	at org.eclipse.jetty.server.Server.handle(Server.java:348)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:452)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:894)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:948)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:851)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:230)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:77)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:606)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:46)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:603)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:538)
	at java.lang.Thread.run(Unknown Source)

**Comment by KEYSERQA** [comment]
Can't update using pip:

C:\Users\xxxxx>pip install -U robotframework-SikuliLibrary==1.0.3
Requirement already up-to-date: robotframework-SikuliLibrary==1.0.3 in c:\users\
xxxxx\appdata\local\programs\python\python36-32\lib\site-packages (1.0.3)

**Comment by rainmanwy** [comment]
could you remove ==1.0.3
i an not sure that 1.0.3 is the latest version in pypi, i could check it the next week.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by KEYSERQA** [comment]
I confirm 1.0.3 is the last version Pypi
https://pypi.org/search/?q=robotframework-SikuliLibrary

**Comment by rainmanwy** [comment]
hi, @KEYSERQA 

Seems the return value from sikuli changed.
I have update the code, but you have to get source code from github, and compile it yourelves.

Or you have to wait i update pypi version

**Comment by KEYSERQA** [comment]
Hi, @rainmanwy .

I don't know how to do that. I will wait for update in PYPI.

Thank you

**Comment by romuluc** [comment]
@rainmanwy 
When will you upgrade the pypi version?

**Comment by rainmanwy** [comment]
As the size of SikuliLibrary over size limit of pypi, i have to wait the answer from pypi.
[#5239](https://github.com/pypa/warehouse/issues/5239)

**Comment by rainmanwy** [comment]
The version in pypi is upgraded to 1.0.4, you may have a try the latest version. Thank you very much!
