### ISSUE TITLE
Failed to install robotframework-desktoplibrary

### ISSUE THREAD

**Issue by Anushri-kookkal** [rainmanwy/robotframework-SikuliLibrary#89]
Having bellow error while installing robotframework-desktoplibrary using "pip install robotframework-desktoplibrary" command

C:\Users\anu>pip install robotframework-desktoplibrary
Collecting robotframework-desktoplibrary
  Using cached https://files.pythonhosted.org/packages/2f/dc/02d773cb2a052a77b226e11a7104d506ecb827798bb4395757104eb0118f/robotframework-desktoplibrary-1.0.1.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\anu\AppData\Local\Temp\pip-install-m9ookcyz\robotframework-desktoplibrary\setup.py", line 4, in <module>
        execfile(join(dirname(abspath(__file__)), 'target', 'src', 'SikuliLibrary', 'version.py'))
    NameError: name 'execfile' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\anu\AppData\Local\Temp\pip-install-m9ookcyz\robotframework-desktoplibrary\

Tried "python setup.py install" as referred in other posts, still no luck.

details of installed libraries and python

C:\Users\anu>pip freeze
Pillow==5.4.1
Pygments==2.3.1
Pypubsub==4.0.0
pywin32==224
robotframework==3.1.1
robotframework-ride==1.7.3.1
robotframework-selenium2library==3.0.0
robotframework-seleniumlibrary==3.3.1
robotframeworklexer==1.1
selenium==3.141.0
six==1.12.0
urllib3==1.24.1
wxPython==4.0.4

C:\Users\anu>python
Python 3.7.0a4 (v3.7.0a4:07c9d85, Jan  9 2018, 07:07:02) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by rainmanwy** [comment]
@Anushri-kookkal , you should use "pip install robotframework-SikuliLibrary" to install the library.
The error is because the old version which only support py2.

**Comment by Anushri-kookkal** [comment]
Thanks @rainmanwy, I did tried that too, unfortunately getting error while import the library to RIDE.
Screenshots attached 
![ride](https://user-images.githubusercontent.com/47237714/52172834-81fcc880-27b2-11e9-804a-f60f1f3f4d26.PNG)
![sikulilibrary_import_error](https://user-images.githubusercontent.com/47237714/52172835-82955f00-27b2-11e9-8021-46b1a7577b3c.PNG)

below

**Comment by rainmanwy** [comment]
Seems there are miss spelling. Should be SikuliLibrary. There is no "i" between L and b.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
