### ISSUE TITLE
Setup failed: No keyword with name 'Add Image Path' found.

### ISSUE THREAD

**Issue by cinhvieira** [rainmanwy/robotframework-SikuliLibrary#95]
I would like to know if there was any modification in the library, because I was able to run my tests and now it presents the following message:

> 
Setup failed:
No keyword with name 'Add Image Path' found.

Also teardown failed:
No keyword with name 'Stop Remote Server' found.
> 

My code:

*** Settings ***
Test Setup        Carrega diretório de imagens
Test Teardown     Stop Remote Server
Library           SikuliLibrary

*** Variables ***
${IMAGE_DIR}      ${CURDIR}\\img
    

*** Test Cases ***
Run the Test Tests
    Opens the windows start menu
 
    
*** Keywords ***
Upload image directory
    Add Image Path    ${IMAGE_DIR}
    
Opens the windows start menu
    Click    windows_start_menu.png

--------------------------------------
Installation is on windows;
First I installed python.
After:  pip install robotframework-SikuliLibrary

**Comment by rainmanwy** [comment]
Do you install JDK in the environment.
And please attach robot log file here, guess there are some information in log.
As it report "no keyword" error, one possible reason is failed to import library!

**Comment by cinhvieira** [comment]
I installed JDK in the environment (1.8.0_201)
[Log.zip](https://github.com/rainmanwy/robotframework-SikuliLibrary/files/3014754/Log.zip)

**Comment by cinhvieira** [comment]
I installed JRE

**Comment by rainmanwy** [comment]
```
Error in file 'C:\Users\Cintia\Documents\TesteDesktopISSDigital\tests\01-Login.robot': Initializing test library 'SikuliLibrary' with no arguments failed: Start sikuli java process failed! Traceback (most recent call last):   File "c:\python27\lib\site-packages\SikuliLibrary\sikuli.py", line 54, in __init__     self.start_sikuli_process(port)   File "c:\python27\lib\site-packages\SikuliLibrary\sikuli.py", line 92, in start_sikuli_process     raise RuntimeError('Start sikuli java process failed!')
```
Sikuli java process start failed!

Could you have a try to start it manually.
The jar file should be in "c:\python27\lib\site-packages\SikuliLibrary\lib"
And you may check "https://github.com/rainmanwy/robotframework-SikuliLibrary#start-server-manually" to get the detail.

**Comment by cinhvieira** [comment]
I made the attempt but presented the following errors

Start service:
C:\Python27\Lib\site-packages\SikuliLibrary\lib>java -jar SikuliLibrary.jar 8000

0 [main] INFO org.robotframework.remoteserver.RemoteServer  - Mapped path / to l
ibrary com.github.rainmanwy.robotframework.sikulilib.SikuliLibrary.
16 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework r
emote server starting
16 [main] INFO org.eclipse.jetty.server.Server  - jetty-7.x.y-SNAPSHOT
31 [main] INFO org.eclipse.jetty.server.handler.ContextHandler  - started o.e.j.
s.ServletContextHandler{/,null}
234 [main] INFO org.eclipse.jetty.server.AbstractConnector  - Started SelectChan
nelConnector@0.0.0.0:8000
234 [main] INFO org.robotframework.remoteserver.RemoteServer  - Robot Framework
remote server started on port 8000.

----------------------------------------------------
`BadStatusLine: No status line received - the server has closed the connection`

**Comment by cinhvieira** [comment]
[Log.zip](https://github.com/rainmanwy/robotframework-SikuliLibrary/files/3043423/Log.zip)

**Comment by rainmanwy** [comment]
hi, from the log, there is error in "Add Image Path"

```
Params: [C:\Users\Cintia\Documents\TesteDesktopISSDigital\tests\img] [error] ImagePath: add: not valid: C:\Users\Cintia\Documents\TesteDesktopISSDigital\tests\img
```
Guess i should check the status of "add image path"

**Comment by bitwisebro** [comment]
@rainmanwy I'm facing the same issue! Have you found any solution yet?? Thanks!
