### ISSUE TITLE
jenkins Run sikuli test, prompt start sikuli java process failed

### ISSUE THREAD

**Issue by jackhao2018** [rainmanwy/robotframework-SikuliLibrary#98]
hello，When I use the jenkins to call the sikulibrary test (mode=NEW), the following picture always appears, and the use case I run locally and the target machine is normal. This type of start sikuli java process failed! occurs only when called with jenkins.
![57745326-4fdafb00-76ff-11e9-9de2-88673f335ccc](https://user-images.githubusercontent.com/45641639/57838551-7ed49800-77f7-11e9-9d87-ace800be4e12.png)
The same case, why can it be run on the local and target machines alone, but the jenkins run will prompt start sikuli java process failed?

**Comment by rainmanwy** [comment]
@jackhao2018 , whether your jenkins is started as windows service.

Not sure this solution could help you [jenkins-selenium-gui-tests-are-not-visible-on-windows](https://stackoverflow.com/questions/9618774/jenkins-selenium-gui-tests-are-not-visible-on-windows)

**Comment by jackhao2018** [comment]
Thank you for your reply, I am now ready to check the firewall, because I found that after I manually started the process, when the browser enters 127.0.0.1:port, the page responds with a 404 error (in my local is the normal display resource path). At the same time, I will also take a serious look at the posts you mentioned here.

**Comment by jackhao2018** [comment]
@rainmanwy hi I just confirmed the reason for the firewall. After I handled the firewall restrictions, the restrictions have been working properly. Thank you very much. By the way, this library is great.

**Comment by RaviGee** [comment]
@jackhao2018 How did you handled firewall change, could you let me know. 
I am getting same error in windows desktop. 

[ ERROR ] Error in file 'C:\Users\d275991\eclipse-workspace\ssp-robot-new\resources\navigation.robot' on line 3: Initializing test library 'SikuliLibrary' with no arguments failed: Start sikuli java process failed!
Traceback (most recent call last):
  File "c:\users\Ra\appdata\local\programs\python\python38-32\lib\site-packages\SikuliLibrary\sikuli.py", line 54, in __init__
    self.start_sikuli_process(port)
  File "c:\users\ra\appdata\local\programs\python\python38-32\lib\site-packages\SikuliLibrary\sikuli.py", line 92, in start_sikuli_process
    raise RuntimeError('Start sikuli java process failed!')
